/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SwcModal {
        "hide": () => Promise<void>;
        "show": () => Promise<void>;
        /**
          * The modal size
         */
        "size": 'sm' | 'md' | 'lg';
        /**
          * The modal static backdrop
         */
        "staticBackdrop": boolean;
        "toggle": () => Promise<void>;
        /**
          * The modal visibility state
         */
        "visible": boolean;
    }
    interface SwcTooltip {
        "content": string;
        "isHtml": boolean;
        "position": 'down' | 'up' | 'right' | 'left';
    }
}
declare global {
    interface HTMLSwcModalElement extends Components.SwcModal, HTMLStencilElement {
    }
    var HTMLSwcModalElement: {
        prototype: HTMLSwcModalElement;
        new (): HTMLSwcModalElement;
    };
    interface HTMLSwcTooltipElement extends Components.SwcTooltip, HTMLStencilElement {
    }
    var HTMLSwcTooltipElement: {
        prototype: HTMLSwcTooltipElement;
        new (): HTMLSwcTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "swc-modal": HTMLSwcModalElement;
        "swc-tooltip": HTMLSwcTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SwcModal {
        /**
          * The modal size
         */
        "size"?: 'sm' | 'md' | 'lg';
        /**
          * The modal static backdrop
         */
        "staticBackdrop"?: boolean;
        /**
          * The modal visibility state
         */
        "visible"?: boolean;
    }
    interface SwcTooltip {
        "content"?: string;
        "isHtml"?: boolean;
        "position"?: 'down' | 'up' | 'right' | 'left';
    }
    interface IntrinsicElements {
        "swc-modal": SwcModal;
        "swc-tooltip": SwcTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "swc-modal": LocalJSX.SwcModal & JSXBase.HTMLAttributes<HTMLSwcModalElement>;
            "swc-tooltip": LocalJSX.SwcTooltip & JSXBase.HTMLAttributes<HTMLSwcTooltipElement>;
        }
    }
}
